/**
 * Reads .env (local) or process.env (cloud) and generates config.js for the browser.
 * Run once after cloning:  node setup.js
 */
const fs = require('fs');
const path = require('path');

const env = {};
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf-8').split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const idx = trimmed.indexOf('=');
    if (idx === -1) return;
    env[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  });
}

// process.env (Vercel / cloud) takes priority over .env file
const get = (k) => process.env[k] || env[k] || '';

const key = get('GOOGLE_MAPS_API_KEY');
if (!key || key === 'YOUR_GOOGLE_MAPS_API_KEY') {
  console.error('Set GOOGLE_MAPS_API_KEY in .env or environment variables before running setup.');
  process.exit(1);
}

const testMode = (get('TEST_MODE') || 'false').toLowerCase() === 'true';
const featureMoreOptions = (get('FEATURE_MORE_OPTIONS') || 'false').toLowerCase() === 'true';
const razorpaySupportUrl = get('RAZORPAY_SUPPORT_URL');
const supabaseUrl = get('SUPABASE_URL');
const supabaseAnonKey = get('SUPABASE_ANON_KEY');

const config = `// Auto-generated by setup.js \u2014 do not edit or commit.\nconst CONFIG = {\n  GOOGLE_MAPS_API_KEY: '${key.replace(/'/g, "\\'")}',\n  TEST_MODE: ${testMode},\n  FEATURE_MORE_OPTIONS: ${featureMoreOptions},\n  RAZORPAY_SUPPORT_URL: '${razorpaySupportUrl.replace(/'/g, "\\'")}',\n  SUPABASE_URL: '${supabaseUrl.replace(/'/g, "\\'")}',\n  SUPABASE_ANON_KEY: '${supabaseAnonKey.replace(/'/g, "\\'")}',\n};\n`;

fs.writeFileSync(path.join(__dirname, 'config.js'), config);
console.log('config.js generated successfully.');
